#!/bin/bash
set -e

# All Kaleidomancy stuff goes in the directory this script is in
KMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"

# Make sure the runtime dir exists
RUNTIMEDIR=$KMDIR/runtime
if ! [ -d $RUNTIMEDIR ]; then
    echo "[enable] runtime not found. Please run setup first"
    exit 1
fi

# If the Reader Lock is not held, no Kaleidomancy Agent or forwarder is running
CMDDIR=$RUNTIMEDIR/cmds
RLOCK=$CMDDIR/rlock
if ! flock -n $RLOCK echo "[enable] Reader Lock is free"; then
    echo "[enable] Reader Lock is held. Kaleidomancy Agent or a Forwarder is already running"
    exit 1
fi

# Fail if running on unsupported host OS
HOSTDIR=$KMDIR/os/$(uname)
if ! [ -d $HOSTDIR ]; then
    echo "[enable] unsupported host OS $(uname). Consider using $KMDIR/run instead"
    exit 1
fi

# OS-Specific Enable
$HOSTDIR/enable.sh

echo "[enable] Waiting for Reader Lock to be held..."
while ! flock -n $RLOCK echo "[enable] Still free..."; do
    sleep 1
done

echo "[enable] Reader Lock is held. Kaleidomancy Agent enabled and started"
exit 0
