#!/bin/bash
set -e

# All Kaleidomancy stuff goes in the directory this script is in
KMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"

if [ $# -eq 0 ]; then
    echo "[forward] Expected one arg to be passed to ssh command"
fi

# Make sure the runtime dir exists
RUNTIMEDIR=$KMDIR/runtime
if ! [ -d $RUNTIMEDIR ]; then
    echo "[forward] runtime not found. Please run setup first"
    exit 1
fi

# If the Reader Lock is not held, no Kaleidomancy Agent or forwarder is running
CMDDIR=$RUNTIMEDIR/cmds
RLOCK=$CMDDIR/rlock
if flock -n $RLOCK echo "[forward] Reader Lock is free"; then
    echo "[forward] Reader Lock is not held. No Kaleidomancy Agent or Forwarder present to consume commands"
    exit 1
fi

REMOTEKMDIR='~/kaleidomancy'
if [ $# -gt 1 ]; then
    REMOTEKMDIR=$2
fi
REMOTERUNTIMEDIR=$REMOTEKMDIR/runtime
REMOTECMDDIR=$REMOTERUNTIMEDIR/cmds
REMOTERLOCK=$REMOTECMDDIR/rlock
REMOTEWLOCK=$REMOTECMDDIR/wlock
REMOTEPIPE=$REMOTECMDDIR/pipe
echo "[forward] using $REMOTEKMDIR as Kaleidomancy dir on remote host"

ssh $1 '
mkdir -p '$REMOTECMDDIR'
touch '$REMOTECMDDIR'/rlock
touch '$REMOTECMDDIR'/wlock
if [ ! -p '$REMOTECMDDIR'/pipe ]; then
    mkfifo '$REMOTECMDDIR'/pipe
fi
if ! flock -n '$REMOTERLOCK' echo "[run] Reader Lock is free" > /dev/null; then
    >&2 echo "[forward] Reader Lock is held. Kaleidomancy Agent or a Forwarder is already running"
    exit 1
fi

>&2 echo "[forward] Forwarding commands from remote Kaleidomancy dir '$1':'$REMOTEKMDIR' to local Kaleidomancy dir '$KMDIR'"
tail -f '$REMOTERUNTIMEDIR'/cmds/pipe
' | xargs -L1 $KMDIR/cmd
