#!/bin/bash
set -e

# All Kaleidomancy stuff goes in the directory this script is in
KMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"

# Make sure the runtime dir exists
RUNTIMEDIR=$KMDIR/runtime
if ! [ -d $RUNTIMEDIR ]; then
    echo "[run] runtime not found. Please run setup first"
    exit 1
fi

# If the Reader Lock is held, the Kaleidomancy Agent or a Forwarder is already running
CMDDIR=$RUNTIMEDIR/cmds
RLOCK=$CMDDIR/rlock
if ! flock -n $RLOCK echo "[run] Reader Lock is free"; then
    echo "[run] Reader Lock is held. Kaleidomancy Agent or a Forwarder is already running"
    exit 1
fi

echo "[run] Starting Kaleidomancy Agent..."
$RUNTIMEDIR/venv/bin/python3 $KMDIR/src/kaleidomancy-agent.py $CMDDIR
EXIT_CODE=$?

echo "[run] Kaleidomancy Agent exited with exit code $EXIT_CODE"
exit 0
