#!/bin/bash
set -e

# All Kaleidomancy stuff goes in the directory this script is in
KMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"

# Fail if pip or virtualenv don't exist
if ! command -v pip &> /dev/null ; then
    echo "[setup] pip command not found. Required for Kaleidomancy agent"
    exit 1
fi
if ! command -v virtualenv &> /dev/null ; then
    echo "[setup] virtualenv command not found. Required for Kaleidomancy agent"
    exit 1
fi

# Make sure there's a directory for runtime stuff
RUNTIMEDIR=$KMDIR/runtime
mkdir -p $RUNTIMEDIR

# Make sure it has a subdirectory for the command pipe and its locks
CMDDIR=$RUNTIMEDIR/cmds
mkdir -p $CMDDIR
touch $CMDDIR/rlock
touch $CMDDIR/wlock
if [ ! -p $CMDDIR/pipe ]; then
    mkfifo $CMDDIR/pipe
fi

# If the Reader Lock is held, the Kaleidomancy Agent or a Forwarder is already running
RLOCK=$CMDDIR/rlock
if ! flock -n $RLOCK echo "[setup] Reader Lock is free"; then
    echo "[setup] Reader Lock is held. Kaleidomancy Agent or a Forwarder is already running"
    exit 1
fi

# Create virtualenv
echo "[setup] Creating virtualenv..."
cd $RUNTIMEDIR
virtualenv venv

# Populate dependencies
echo "[setup] Populating dependencies..."
cd $KMDIR
./runtime/venv/bin/python3 -m pip install -r ./src/requirements.txt

echo "Setup complete. You can use the 'run' or 'enable' scripts now"
exit 0
